SemanticUIExam/config/routes.rb
Rails.application.routes.draw do
  resources :boards

end

SemanticUIExam/app/models/board.rb
class Board < ActiveRecord::Base
end

SemanticUIExam/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

SemanticUIExam/app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.all
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'Board was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:name, :title, :contents)
    end
end

SemanticUIExam/app/helpers/boards_helper.rb
module BoardsHelper
end

SemanticUIExam/app/views/boards/_form.html.erb
<div class="ui container">
  <div class="ui grid">
    <div class="six wide column">
      <%= form_for @board, :class => 'ui form' do |f| %>
          <% if @board.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

                <ul>
                  <% @board.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
          <% end %>

          <%= f.label :name %><br>
          <div class="field">
            <%= f.text_field :name %>
          </div>

          <%= f.label :title %><br>
          <div class="field">
            <%= f.text_field :title %>
          </div>

          <%= f.label :contents %><br>
          <div class="field">
            <%= f.text_area :contents, :rows => 4 %>
          </div>
          <div class="actions">
            <%= f.submit :submit, :class => 'ui button' %>
            <%= link_to 'Back', boards_path, :class => 'ui button' %>
          </div>
      <% end %>
    </div>
  </div>
</div>

SemanticUIExam/app/views/boards/edit.html.erb
<h1>Editing Board</h1>

<%= render 'form' %>

SemanticUIExam/app/views/boards/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="ui header">Listing Boards</h1>

<table class="ui celled table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th>Contents</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @boards.each do |board| %>
      <tr>
        <td><%= board.name %></td>
        <td><%= board.title %></td>
        <td><%= board.contents %></td>
        <td><%= link_to 'Show', board, :class => 'ui primary button' %></td>
        <td><%= link_to 'Edit', edit_board_path(board), :class => 'ui secondary button' %></td>
        <td><%= link_to 'Destroy', board, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'ui red basic button' %></td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
  <tr><th colspan="6">
    <div class="ui right floated pagination menu">
      <a class="icon item">
        <i class="left chevron icon"></i>
      </a>
      <a class="item">1</a>
      <a class="item">2</a>
      <a class="item">3</a>
      <a class="item">4</a>
      <a class="icon item">
        <i class="right chevron icon"></i>
      </a>
    </div>
  </th>
  </tfoot>
</table>

<br>

<%= link_to 'New Board', new_board_path, :class => 'ui primary button' %>

SemanticUIExam/app/views/boards/new.html.erb
<h4 class="ui dividing header">New Article</h4>
<%= render 'form' %>

SemanticUIExam/app/views/boards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @board.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @board.title %>
</p>

<p>
  <strong>Contents:</strong>
  <%= @board.contents %>
</p>

<%= link_to 'Edit', edit_board_path(@board) %> |
<%= link_to 'Back', boards_path %>

SemanticUIExam/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SemanticUIExam</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>